pm_robot_description:
  X_Axis_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  X_Axis_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: X_Axis_Joint

  Y_Axis_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  Y_Axis_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Y_Axis_Joint

  Z_Axis_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  Z_Axis_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Z_Axis_Joint

  Gripper_Rot_Plate_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  Gripper_Rot_Plate_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Gripper_Rot_Plate_Joint  

  Glue_Cartridge_Flap_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  Glue_Cartridge_Flap_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Glue_Cartridge_Flap_Joint

  Glue_Cartridge_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  Glue_Cartridge_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Glue_Cartridge_Joint

  EQ_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  EQ_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: EQ_Joint
  
  Gonio_Right_Stage_1_Upper_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  Gonio_Right_Stage_1_Upper_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Gonio_Right_Stage_1_Upper_joint

  Gonio_Right_Stage_2_Upper_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  Gonio_Right_Stage_2_Upper_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Gonio_Right_Stage_2_Upper_Joint
  
  Camera_Calibartion_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  Camera_Calibartion_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Camera_Calibartion_Joint

  Gonio_Left_Stage_1_Upper_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  Gonio_Left_Stage_1_Upper_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Gonio_Left_Stage_1_Upper_Joint 
  
  Gonio_Left_Stage_2_Upper_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  Gonio_Left_Stage_2_Upper_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Gonio_Left_Stage_2_Upper_Joint 

  UV_Cart_Left_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  UV_Cart_Left_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: UV_Cart_Left_Joint 
  
  UV_Module_Left_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  UV_Module_Left_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: UV_Module_Left_Joint
  
  UV_Cart_Right_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  UV_Cart_Right_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: UV_Cart_Right_Joint 
  
  UV_Module_Right_Joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  UV_Module_Right_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: UV_Module_Right_Joint



  gazebo_ros_control:
    pid_gains:
      X_Axis_Joint:
        p: 10.0
        i: 1
        d: 100

      Y_Axis_Joint:
        p: 100.0
        i: 1
        d: 100

      Z_Axis_Joint:
        p: 100.0
        i: 1
        d: 100

      Gripper_Rot_Plate_Joint:
        p: 100.0
        i: 0.01
        d: 0.0  
      
      Glue_Cartridge_Flap_Joint:
        p: 100.0
        i: 0.01
        d: 10.0
        
      Glue_Cartridge_Joint:
        p: 100.0
        i: 0.01
        d: 10.0

      EQ_Joint:
        p: 100.0
        i: 0.01
        d: 10.0

      Gonio_Right_Stage_1_Upper_joint:
        p: 100.0
        i: 0.01
        d: 0.0   
      
      Gonio_Right_Stage_2_Upper_Joint:
        p: 100.0
        i: 0.01
        d: 0.0  
      
      Camera_Calibartion_Joint:
        p: 100.0
        i: 0.01
        d: 10.0      

      Gonio_Left_Stage_1_Upper_Joint:
        p: 100.0
        i: 0.01
        d: 0.0  
      
      Gonio_Left_Stage_2_Upper_Joint:
        p: 100.0
        i: 0.01
        d: 0.0  
      
      UV_Cart_Left_Joint:
        p: 100.0
        i: 0.01
        d: 10.0   
      
      UV_Module_Left_Joint:
        p: 100.0
        i: 0.01
        d: 10.0  

      UV_Cart_Right_Joint:
        p: 100.0
        i: 0.01
        d: 10.0   
      
      UV_Module_Right_Joint:
        p: 100.0
        i: 0.01
        d: 10.0  
